query getArticle($relativePath: String!) {
  article(relativePath: $relativePath) {
    ...ArticlePartsOverride
  }
}

query getCategory($relativePath: String) {
  category(relativePath: $relativePath) {
    ...CategoryParts
    related {
      category {
        ... on Category {
          _sys {
            filename
          }
          ...CategoryParts
        }
      }
    }
  }
}

query getArticlesByCategory($category: String) {
  articleConnection(
    filter: {
      advanced:{ categories: { category: { category: { slug: { eq: $category } } } } } 
    }
  ) {
    edges {
      node {
        _sys {
          filename
        }
        ...ArticlePartsOverride
      }
    }
  }
}

query getArticlesByAuthor($author: String) {
  articleConnection(
    filter: { advanced: { authors: { author: { author: { slug: { eq: $author } } } } } }
  ) {
    edges {
      node {
        _sys {
          filename
        }
        ...ArticlePartsOverride
      }
    }
  }
}
